stages:
  - name: binary
    if: tag IS present

jobs:
  include:
    - stage: binary
      os: linux
      services:
        - docker

      before_install:
        - docker pull mattipaksula/gem2exe
      script:
        - mkdir releases
        - docker run --name gem2exe -it --volume $(pwd):/gem mattipaksula/gem2exe local --path /gem --out /tmp/gmortar gmortar
        - docker cp gem2exe:/tmp/gmortar releases/gmortar-linux-amd64-${TRAVIS_TAG}

    - stage: binary
      os: osx
      sudo: required
      rvm:
        - "2.6"
      before_install:
        - curl -L https://github.com/matti/gem2exe/releases/download/v0.3.2/gem2exe-darwin-amd64-v0.3.2.gz | gunzip - > gem2exe
        - chmod a+x gem2exe
        - sudo mv gem2exe /usr/local/bin/gem2exe
        - gem2exe setup
      script:
        - mkdir releases
        - gem2exe local --out releases/gmortar-darwin-amd64-${TRAVIS_TAG} gmortar

deploy:
  - provider: releases
    api_key:
      secure: "peMS9lsA46iQHeLOhj/PRsd2bYIYpN0RlatAmV62AnuTyne+yx4cSaWsAONJelNgX8zKL8iNBmX6c2jdm3GhLVwKldDnwOQvKl1nJTqf0OZQJIg5r+YG4KAmWDkr93POsUaSOwAiK6zp2xK17YoKLdCvIFwj+gJNHSa1r2QmMCi/vnQiBUCHTB+7eqgoW1Bu5c2BfKHZBFUvc4MZUWCMqUaOBpqSdW1iiF0nKT9gvQ0GCXVrTd2libf0nEDuHSF0DIAqjVbI+GAKRUsKTQhTM2js3Sbe4rPZerJ1Gde+59j7h8e8T91CwpxpRUeZfmDQg7ABygXPxhzFylieIzP+1iym7VT0X6kty0fOvB/Q8U802K5iqrcmCieSHp2EV+bncU3OaPDDGb9ABj4BHilH4NTl+dhHaaXU7XML8zELqpZ+AYyswEYWBRQkDxm/t0lp1pvXnS/0hHO3jlC1jY8j6IDRMyWcdOa95By1+ExKKqpJCojan1b6efyl0egyJaLlmv4CSJtWDh+VB9yJo9WBg0fsO82nGPSkNlhukd7JzQobU5/jqhbndx2Jp5eRUshF5LLkxUHTv64t121d8kDY1WMmYw/Zv/ZZCOI6qKOyfPleSdmbLNnEDgnALZ8qyatvB2pe0VkS8x8bYcxfgcG4M8ldhmxURw82xug+WLdO5fc="
    file_glob: true
    file: releases/*
    skip_cleanup: true
    on:
      tags: true
  - provider: rubygems
    api_key:
      secure: "dwuwaBtcqJf0gd2ZpNTYp7hsoN5wT25K8XcM3sfesDY5HZ7T0RfDSRjZ1zyoFRuC/DfSZx09IHYwjBr3ieHqVVflitrrnScgWIahi3HI0HtsZOZiBL0diqm/PC8ODjLsIaD3Ny4B9yYDh4jvd4mB8HpU+KHe5iKHpnbnPhKpHxF4HRq9gwl2/C3cD5nfwq6Wmn/IEArrZ4VOH8NdjHRXbhYoDN+t4wIILrgA3axE0+t7GWot3Oe25UQehfNCdLotQWY7cgJWUYSQ6VwODft3xrMzur+sxra8Blk7NrJm3nmCh5Si0DeEFgist/KHj1rA2sh1UKgMaT9lgm4NyTaLlXsgi492OwuT1piLfiQTOS3yXvz+FGCE0mQEdSIBTTocg8gWtUjRIH/TcbkeZmFY1m0vZT1cX9Lpo7GEGpfabg6a8YkcaTw6mpdt7evNBJ2ckYuP0DePsJHlKcGG4MtBbh15BwLlHiNJeTY9TE5LVAUpaFcdwIq/rPvtM/J2VTP7xKuxTj8b2nx9ianJFTE6XW+QTthRh8K9UlBOizpYyOt0kpJi+Fd3o5p0ZrtS6zGZwja4WcwYHk7WRHdq4kZ6WTmIfk2dBa6x0qkzpA64EJy0McW5YXoeQc+yPkEKkikuFdZnVt0zIiShNvTjkMdMouS1WsMchYROwNwyt5mzG4w="
    on:
      branch: master
