stages:
  - name: binary
    if: tag IS present

jobs:
  include:
    - stage: binary
      os: osx
      sudo: required
      rvm:
        - "2.6"
      before_install:
        - curl -L https://github.com/matti/gem2exe/releases/download/v0.3.2/gem2exe-darwin-amd64-v0.3.2.gz | gunzip - > gem2exe
        - chmod a+x gem2exe
        - sudo mv gem2exe /usr/local/bin/gem2exe
        - gem2exe setup
      script:
        - mkdir releases
        - gem2exe local --out releases/gmortar-darwin-amd64-${TRAVIS_TAG} gmortar

deploy:
  - provider: releases
    api_key:
      secure: "IrBB7cdUzZcKLnuoiiuU0ZDKrONSSmC7sGWU3xapTKnTA4t1vvcGqRA4y48DvfiIQKWsMhgnL2yX/1IoTmPsDWtTxtlbDm2qMU9fEjg5xbD5K1EUOOqPbhCFKZ5ANsMENZBQ2wAW1MnnMoiD1YFsOCS7rRSILKXmQy5KzS3g8QrKONQlAOfFL1PIKPjP6ZR9jzHC7kpxzBMuyqbHUbclz1XRQaNlZYwt927sNK3rzoU6JhRIwuV5rIf67leyaS6643PCsMuf9WbXF2Se7DgmFLUtlPd9KiP0ae8ArTX6PSikDdwNDG6t2lp6NYAUTGPO7n1MyTSLou4tpqGrJrubOTqpE9ndB2mhoB+qkQfbs0VpAIGJc52eri+vy5MEhvLdZo5A3Hmb7cF0xWs1pWam/1CR6CvfLDGU2JljNqCZdhgZCc7d1mZdizeLYTONLVCjzi6K82PMwRmD4QCsXGMDckcaZgcBXHfMeCYiiqAU26KTVzVh9bZnNYXxeNFtg7i7O3Z7cyGeA2e8EVT/pUv0lMiihHUr0YnPqJGN2Aacweob7i3Dyu6hqMj6LjEi02vDUPDTZmkiZxRFprNv3Iz4WaQE1oc2xXSbgawmzWcUcL2PHk8p+czqowiaMm3CkZeKdMibrumGUHNy8lu2F5/gr54Tmxk7SpqG4pz+OpIGNXA="
    file_glob: true
    file: releases/*
    skip_cleanup: true
    on:
      tags: true
  - provider: rubygems
    api_key:
      secure: "dwuwaBtcqJf0gd2ZpNTYp7hsoN5wT25K8XcM3sfesDY5HZ7T0RfDSRjZ1zyoFRuC/DfSZx09IHYwjBr3ieHqVVflitrrnScgWIahi3HI0HtsZOZiBL0diqm/PC8ODjLsIaD3Ny4B9yYDh4jvd4mB8HpU+KHe5iKHpnbnPhKpHxF4HRq9gwl2/C3cD5nfwq6Wmn/IEArrZ4VOH8NdjHRXbhYoDN+t4wIILrgA3axE0+t7GWot3Oe25UQehfNCdLotQWY7cgJWUYSQ6VwODft3xrMzur+sxra8Blk7NrJm3nmCh5Si0DeEFgist/KHj1rA2sh1UKgMaT9lgm4NyTaLlXsgi492OwuT1piLfiQTOS3yXvz+FGCE0mQEdSIBTTocg8gWtUjRIH/TcbkeZmFY1m0vZT1cX9Lpo7GEGpfabg6a8YkcaTw6mpdt7evNBJ2ckYuP0DePsJHlKcGG4MtBbh15BwLlHiNJeTY9TE5LVAUpaFcdwIq/rPvtM/J2VTP7xKuxTj8b2nx9ianJFTE6XW+QTthRh8K9UlBOizpYyOt0kpJi+Fd3o5p0ZrtS6zGZwja4WcwYHk7WRHdq4kZ6WTmIfk2dBa6x0qkzpA64EJy0McW5YXoeQc+yPkEKkikuFdZnVt0zIiShNvTjkMdMouS1WsMchYROwNwyt5mzG4w="
    on:
      branch: master
